"""
backend/app/schemas/feedback.py
=================================
PURPOSE:
  Pydantic schemas for the /feedback endpoint.

WHY FEEDBACK MATTERS FOR ML:
  User feedback closes the loop:
    1. Model makes prediction
    2. User sees real outcome
    3. User tells us if the model was right or wrong
    4. We store (input, model_output, true_label) → training data
    5. Model is retrained on corrected data → improves over time

FEEDBACK TYPES:
  Explicit → user clicks thumbs up/down or enters the true label
  Implicit → rules automatically generate feedback (e.g. if a
             "fraud" prediction led to a chargeback → confirmed fraud)
"""

from datetime import datetime
from typing import Any, List, Optional

from pydantic import BaseModel, Field, field_validator


class FeedbackRequest(BaseModel):
    """
    Body for POST /feedback

    request_id    — the inference request_id this feedback is for
                    (links feedback back to the exact prediction)
    rating        — 1 (correct) or 0 (incorrect) — thumbs up/down
    true_label    — optional: the actual correct answer
                    (e.g., the transaction WAS fraud → true_label=1)
    comment       — optional free-text reasoning
    feedback_type — "explicit" (user) or "implicit" (automated rule)

    Example:
    {
      "request_id": "req-abc-123",
      "rating": 0,
      "true_label": 1,
      "comment": "Was actually fraudulent — chargeback received"
    }
    """
    request_id: str = Field(
        ...,
        description="The inference request_id this feedback refers to.",
        examples=["req-abc-123"],
    )
    rating: int = Field(
        ...,
        ge=0,
        le=1,
        description="1 = prediction was correct, 0 = prediction was wrong.",
        examples=[0],
    )
    true_label: Optional[Any] = Field(
        default=None,
        description="The actual ground-truth label. Used to build training data.",
        examples=[1],
    )
    comment: Optional[str] = Field(
        default=None,
        max_length=1000,
        description="Optional free-text explanation.",
        examples=["Chargeback confirmed — transaction was fraudulent."],
    )
    feedback_type: str = Field(
        default="explicit",
        description="'explicit' = user-submitted. 'implicit' = auto-generated by rules.",
    )

    @field_validator("feedback_type")
    @classmethod
    def validate_type(cls, v: str) -> str:
        allowed = {"explicit", "implicit"}
        if v not in allowed:
            raise ValueError(f"feedback_type must be one of {allowed}")
        return v


class FeedbackResponse(BaseModel):
    """Response for POST /feedback (successful submission)."""
    feedback_id: str = Field(..., description="Unique ID of the stored feedback document.")
    request_id: str
    message: str = "Feedback recorded. Thank you!"


class FeedbackDocument(BaseModel):
    """
    Full feedback document stored in MongoDB 'feedback' collection.

    Includes all submitted fields + derived metadata used for:
      - Auto-generating labeled training data
      - Accuracy metric calculations (how often was the model right?)
      - Drift signals (if accuracy is dropping over time)
    """
    feedback_id: str
    request_id: str
    user_id: str
    model_version_id: str
    model_version_tag: str

    # From the submitted feedback
    rating: int
    true_label: Optional[Any] = None
    comment: Optional[str] = None
    feedback_type: str = "explicit"

    # Copied from the original inference log (for training data)
    input_features: Optional[dict] = None
    model_prediction: Optional[Any] = None
    model_confidence: Optional[float] = None

    # Derived
    is_correct: bool  # rating == 1

    created_at: datetime

    model_config = {"from_attributes": True}


class FeedbackStats(BaseModel):
    """
    Aggregated feedback statistics for a model version.
    Returned by GET /metrics endpoint.
    """
    model_version_tag: str
    total_feedback: int
    correct_predictions: int
    incorrect_predictions: int
    accuracy_from_feedback: float = Field(
        ..., description="Accuracy derived from feedback (correct / total)"
    )
    average_confidence: float
    period_days: int = Field(..., description="Stats over the last N days")
